# Generated by Django 3.2.7 on 2021-11-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=60)),
                ('positive', models.BigIntegerField(default=0)),
                ('death', models.BigIntegerField(default=0)),
                ('recovered', models.BigIntegerField(default=0)),
            ],
        ),
    ]
