# Generated by Django 3.2.8 on 2021-10-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
